name: Publish Artifacts
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install GPG
        run: |
          brew install gpg

      - name: Import GPG Key
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          # Install gpg secret key
           echo "$SIGNING_KEY" | gpg --dearmor > ${HOME}/secring.gpg

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Add Gradle Properties
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          echo "mavenCentralUsername = ${MAVEN_CENTRAL_USERNAME}" >> gradle.properties
          echo "mavenCentralPassword = ${MAVEN_CENTRAL_PASSWORD}" >> gradle.properties
          echo "signing.keyId = ${SIGNING_KEY_ID}" >> gradle.properties
          echo "signing.password = ${SIGNING_KEY_PASSWORD}" >> gradle.properties
          echo "signing.secretKeyRingFile = ${HOME}/secring.gpg" >> gradle.properties

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Publish To Maven Central
        run: |
          ./gradlew eungabi:publishAndReleaseToMavenCentral --no-configuration-cache