name: Release MementoUI

on:
  push:
    tags:
      - '*.*.*-ios'

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME%-ios}" >> $GITHUB_OUTPUT

      - name: Build XCFramework
        run: ./gradlew :memento-ui:assembleMementoUiXCFramework -Pversion=${{ steps.get_version.outputs.VERSION }}

      - name: Create Zip from XCFramework
        run: |
          cd memento-ui/build/XCFrameworks/release
          zip -r MementoUi.xcframework.zip MementoUi.xcframework

      - name: Compute Checksum
        id: checksum
        run: |
          cd memento-ui/build/XCFrameworks/release
          CHECKSUM=$(swift package compute-checksum MementoUi.xcframework.zip)
          echo "CHECKSUM=$CHECKSB" >> $GITHUB_OUTPUT
          cd ../../../..

      - name: Update Package.swift
        run: |
          URL="https://github.com/easternkite/memento/releases/download/${{ steps.get_version.outputs.VERSION }}/MementoUi.xcframework.zip"
          CHECKSUM="${{ steps.checksum.outputs.CHECKSUM }}"
          sed -i '' "s|url: ".*"|url: "${URL}",|" Package.swift
          sed -i '' "s|checksum: ".*"|checksum: "${CHECKSUM}")|" Package.swift

      - name: Commit and Push Package.swift
        run: |
          git config user.name "takealook-bot"
          git config user.email "takealookbot@gmail.com"
          git add Package.swift
          git commit -m "Update Package.swift to version ${{ steps.get_version.outputs.VERSION }}"
          git push origin HEAD:${{ github.ref_name }}

      - name: Create new tag
        run: |
          git tag ${{ steps.get_version.outputs.VERSION }}
          git push origin ${{ steps.get_version.outputs.VERSION }}

      - name: Create Release and Upload Asset
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} \
            memento-ui/build/XCFrameworks/release/MementoUi.xcframework.zip \
            --title "Release ${{ steps.get_version.outputs.VERSION }}" \
            --notes "Release for version ${{ steps.get_version.outputs.VERSION }}"
